### ISSUE TITLE
autoPvP issues

### ISSUE THREAD

**Issue by monsenanna** [MatthieuBonne/CQAutomater#70]
AutoPvP hasn't been working for my main account for the past couple weeks, but works fine on alt accounts, I'm using most recent version on all 3.. Unsure as to why that may be.

**Comment by Vitae666** [comment]
Still having this? Figured it out? Something with the settings that might be different between them?
Question: Not that I have the time (or hell, the CPU power) to run alts, but how do you do it with CQA/CQMC/Calc? Different folders with the same files? Or do you build your own and change the exe file names with an edit to line 17 of Form1.cs in each build with:
        public const string SettingsFilename = "Alt1_Settings.json";
        public const string SettingsFilename = "Alt2_Settings.json";
        public const string SettingsFilename = "Main_Settings.json";
then run Alt1_CQA.exe, Alt2_CQA.exe, and Main_CQA.exe all in the same folder?
I may not have the time, but that doesn't mean I haven't thought of how to do it without multiple folders ;-)
I realize tho, this method would be HELL with logs since they cause crashes in CQA when there's too much writing to them at the same time.

**Comment by MatthieuBonne** [comment]
PvP has CQ-related issues that should be fixed in 4.8.4 (yes, I have faith !). I'm almost certain it's not CQA-related.

I have no alt, but yes, one folder per alt should run fine I guess.
